### PR TITLE
List of computers on Employee Edit

### PR DESCRIPTION
**Pull request by therealrmac**
Fixes for #4

Changes proposed in this pull request:
- Added the Logic for getting back available computers that can be added to an employee
- Put loop in the view model to iterate over the selected items

How to test:
- Run the program / go to employees
- go to edit an employee and there should only be one computer that comes back

NOTE: On this branch you still cannot save the new laptop that you've added yet.

@PushyDonkey/

### CODE REVIEW

**Comment by KyleKellums** [comment]
Tested on my computer. Everything functioned as expected.

**Comment by Kmille15** [comment]
Working!

**Comment by jeffdylansmith** [comment]
I can see the one comp but I can't save it.

**Comment by RillistikPete** [comment]
Working

**Pull request merged**
