### PR TITLE
Kk train prog details

### PR DESCRIPTION
**Pull request by KyleKellums**
## Status
Choose:
**READY TO TEST**

## Description
A user should be able to view a list of training programs, and the details of that program, with a list of attending Employees.

## Steps to Test or Reproduce
```
git fetch --all
git branch -avv
git checkout kk-TrainProgDetails
``` 
- Enter ```Update-Database``` in the console
- Run the Program
- Click on Training Programs
- Click on 'Details' on a Training Program

## Impacted Areas in Application
List general components of the application that this PR will affect:
- TrainingProgramController.cs
- TrainingProgramViewModel.cs
- TrainingProgram/Details.cshtml

### CODE REVIEW

**Comment by therealrmac** [comment]
👍 👍

**Comment by jeffdylansmith** [comment]
So the details are working fine.  I can't edit a training program.  It gives me a 'name field is required' error even if I put something in there.  Also, shouldn't the name field carry over from when it was clicked?  Probably outside the scope of this ticket but anyway...

**Comment by Kmille15** [comment]
Working!

**Comment by Kmille15** [comment]
if statement works for when no employees are assigned to training program

**Pull request merged**
