### PR TITLE
Pete and I created training program model and computer controller

### PR DESCRIPTION
**Pull request by Kmille15**
Changes proposed in this pull request:
-Created the Model for Training Program
-Created the Controller for Computer
-

How to test:
- git fetch
- git checkout km-branch1
-Check that all names are included in the Training Program Model and spelled correctly
-Check that get, put, post and delete methods are available in the Computer Controller

@PushyDonkey/

### CODE REVIEW

**Comment by jeffdylansmith** [comment]
Actually, we need to fill out that training program model!

**Comment by therealrmac** [comment]
We forgot to put something in the trainginProgram but we're fixing it.

**Comment by RillistikPete** [comment]
👍

**Comment by therealrmac** [comment]
Everything is in place now.

**Pull request merged**
