### PR TITLE
employee details complete

### PR DESCRIPTION
**Pull request by therealrmac**
Fixes for #3 

Changes proposed in this pull request:
- made changes to the controller to include the join tables
- made changes to the detail.cshtml for employee to get the data needed to display
- made changes to the seed file and database file

How to test:
- pull my branch 
- run the ISS express
- go to /employees and click details to view a selected employee detail

NOTE: if you are creating or editing an employee, there won't be a place to input a computer or training program.

@PushyDonkey/

### CODE REVIEW

**Comment by jeffdylansmith** [comment]
So I am able to add and edit current employees but I get  "SqlException: invalid object name 'TraingPrgEmp'" error when I try to view details.

**Comment by therealrmac** [comment]
You might need to do a new migration and then update database again

**Comment by therealrmac** [comment]
Its probably throwing that error because there is no TrainingPrgEmp table

**Comment by KyleKellums** [comment]
I pulled down the most recently updated version of the branch. Employees and Employee detail functioned as expected.

**Comment by Kmille15** [comment]
Eureka! Detail section working

**Comment by jeffdylansmith** [comment]
Finally!  Its working for me!!!

**Pull request merged**
